// Code generated by tony-codegen. DO NOT EDIT.

package dfile

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts DiffFile to a Tony IR node.
func (s *DiffFile) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Seq
	irMap["Seq"] = ir.FromInt(int64(s.Seq))

	// Field: Path
	irMap["Path"] = ir.FromString(s.Path)

	// Field: Timestamp
	irMap["Timestamp"] = ir.FromString(s.Timestamp)

	// Field: Diff (optional)
	if s.Diff != nil {
		if s.Diff == nil {
			irMap["Diff"] = ir.Null()
		} else {
			irMap["Diff"] = s.Diff
		}
	}

	// Field: Pending
	irMap["Pending"] = ir.FromBool(s.Pending)

	// Field: Inputs
	irMap["Inputs"] = ir.FromInt(int64(s.Inputs))

	// Create IR node with schema tag
	return ir.FromMap(irMap).WithTag("!diff-file"), nil
}

// FromTonyIR populates DiffFile from a Tony IR node.
func (s *DiffFile) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for DiffFile, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		switch fieldName.String {
		case "Seq":
			// Field: Seq
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "Seq", fieldNode.Type)
			}
			s.Seq = int64(*fieldNode.Int64)
		case "Path":
			// Field: Path
			if fieldNode.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "Path", fieldNode.Type)
			}
			s.Path = fieldNode.String
		case "Timestamp":
			// Field: Timestamp
			if fieldNode.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "Timestamp", fieldNode.Type)
			}
			s.Timestamp = fieldNode.String
		case "Diff":
			s.Diff = fieldNode
		case "Pending":
			// Field: Pending
			if fieldNode.Type != ir.BoolType {
				return fmt.Errorf("field %q: expected bool, got %v", "Pending", fieldNode.Type)
			}
			s.Pending = fieldNode.Bool
		case "Inputs":
			// Field: Inputs
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "Inputs", fieldNode.Type)
			}
			s.Inputs = int(*fieldNode.Int64)
		}
	}

	return nil
}

// ToTony converts DiffFile to Tony format bytes.
func (s *DiffFile) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates DiffFile.
func (s *DiffFile) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
