// Code generated by tony-codegen. DO NOT EDIT.

package embedptr

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Base to a Tony IR node.
func (s *Base) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: ID
	irMap["id"] = ir.FromString(string(s.ID))

	// Field: Note
	if s.Note != "" {
		irMap["note"] = ir.FromString(string(s.Note))
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Base from a Tony IR node.
func (s *Base) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Base, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "id":
			// Field: ID
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "id", fieldNodeUnwrapped.Type)
			}
			s.ID = string(fieldNodeUnwrapped.String)
		case "note":
			// Field: Note
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "note", fieldNodeUnwrapped.Type)
			}
			s.Note = string(fieldNodeUnwrapped.String)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Base", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Base to Tony format bytes.
func (s *Base) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Base.
func (s *Base) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts S to a Tony IR node.
func (s *S) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: ID
	if s.Base != nil {
		irMap["id"] = ir.FromString(string(s.ID))
	}

	// Field: Note
	if s.Base != nil {
		if s.Note != "" {
			irMap["note"] = ir.FromString(string(s.Note))
		}
	}

	// Field: Name
	irMap["name"] = ir.FromString(string(s.Name))

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates S from a Tony IR node.
func (s *S) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for S, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "id":
			if s.Base == nil {
				s.Base = &Base{}
			}
			// Field: ID
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "id", fieldNodeUnwrapped.Type)
			}
			s.ID = string(fieldNodeUnwrapped.String)
		case "note":
			if s.Base == nil {
				s.Base = &Base{}
			}
			// Field: Note
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "note", fieldNodeUnwrapped.Type)
			}
			s.Note = string(fieldNodeUnwrapped.String)
		case "name":
			// Field: Name
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "name", fieldNodeUnwrapped.Type)
			}
			s.Name = string(fieldNodeUnwrapped.String)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for S", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts S to Tony format bytes.
func (s *S) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates S.
func (s *S) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts T to a Tony IR node.
func (s *T) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Note
	if s.Note != "" {
		irMap["note"] = ir.FromString(string(s.Note))
	}

	// Field: ID
	irMap["id"] = ir.FromString(string(s.ID))

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates T from a Tony IR node.
func (s *T) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for T, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "note":
			// Field: Note
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "note", fieldNodeUnwrapped.Type)
			}
			s.Note = string(fieldNodeUnwrapped.String)
		case "id":
			// Field: ID
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "id", fieldNodeUnwrapped.Type)
			}
			s.ID = string(fieldNodeUnwrapped.String)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for T", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts T to Tony format bytes.
func (s *T) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates T.
func (s *T) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
