// Code generated by tony-codegen. DO NOT EDIT.

package floats

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Host to a Tony IR node.
func (s *Host) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: F
	irMap["f"] = ir.FromFloat(float64(s.F))

	// Field: Xs
	if len(s.Xs) > 0 {
		slice := make([]*ir.Node, len(s.Xs))
		for i, v := range s.Xs {
			slice[i] = ir.FromFloat(float64(v))
		}
		irMap["xs"] = ir.FromSlice(slice)
	}

	// Field: M
	if len(s.M) > 0 {
		mapNodes := make(map[string]*ir.Node)
		for k, v := range s.M {
			mapNodes[k] = ir.FromFloat(float64(v))
		}
		irMap["m"] = ir.FromMap(mapNodes)
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Host from a Tony IR node.
func (s *Host) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Host, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "f":
			// Field: F
			if fieldNodeUnwrapped.Float64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "f", fieldNodeUnwrapped.Type)
			}
			s.F = float64(*fieldNodeUnwrapped.Float64)
		case "xs":
			// Field: Xs
			if fieldNodeUnwrapped.Type == ir.ArrayType {
				slice := make([]float64, len(fieldNodeUnwrapped.Values))
				for i, v := range fieldNodeUnwrapped.Values {
					ctx := fmt.Sprintf("slice element %d", i)
					var elem float64
					if v.Float64 == nil {
						return fmt.Errorf("%s: expected number, got %v", ctx, v.Type)
					}
					elem = float64(*v.Float64)
					slice[i] = float64(elem)
				}
				s.Xs = slice
			} else {
				return fmt.Errorf("%s: expected array, got %v", "field \"xs\"", fieldNodeUnwrapped.Type)
			}
		case "m":
			// Field: M
			if fieldNodeUnwrapped.Type == ir.ObjectType {
				m := make(map[string]float64)
				irMap := ir.ToMap(fieldNodeUnwrapped)
				for k, v := range irMap {
					ctx := fmt.Sprintf("map value at key %q", k)
					var val float64
					if v.Float64 == nil {
						return fmt.Errorf("%s: expected number, got %v", ctx, v.Type)
					}
					val = float64(*v.Float64)
					m[k] = val
				}
				s.M = m
			} else {
				return fmt.Errorf("%s: expected object, got %v", "field \"m\"", fieldNodeUnwrapped.Type)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Host", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Host to Tony format bytes.
func (s *Host) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Host.
func (s *Host) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
