// Code generated by tony-codegen. DO NOT EDIT.

package server

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Config to a Tony IR node.
func (s *Config) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Schema (optional)
	if s.Schema != nil {
		irMap["schema"] = s.Schema
	}

	// Field: Snapshot (optional)
	if s.Snapshot != nil {
		node, err = s.Snapshot.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["snapshot"] = node
	}

	// Field: Tx (optional)
	if s.Tx != nil {
		node, err = s.Tx.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["tx"] = node
	}

	// Field: Compaction (optional)
	if s.Compaction != nil {
		node, err = s.Compaction.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["compaction"] = node
	}

	// Field: Retention (optional)
	if s.Retention != nil {
		node, err = s.Retention.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["retention"] = node
	}

	// Field: Storage (optional)
	if s.Storage != nil {
		node, err = s.Storage.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["storage"] = node
	}

	return ir.FromMap(irMap).WithTag("!config"), nil
}

// FromTonyIR populates Config from a Tony IR node.
func (s *Config) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Config, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "schema":
			if gomap.GetUnmapComments(opts...) {
				s.Schema = fieldNode
			} else {
				s.Schema = fieldNodeUnwrapped
			}
		case "snapshot":
			// Field: Snapshot
			s.Snapshot = &SnapshotConfig{}
			if err := s.Snapshot.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		case "tx":
			// Field: Tx
			s.Tx = &TxConfig{}
			if err := s.Tx.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		case "compaction":
			// Field: Compaction
			s.Compaction = &CompactionConfig{}
			if err := s.Compaction.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		case "retention":
			// Field: Retention
			s.Retention = &RetentionConfig{}
			if err := s.Retention.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		case "storage":
			// Field: Storage
			s.Storage = &StorageConfig{}
			if err := s.Storage.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Config", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Config to Tony format bytes.
func (s *Config) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Config.
func (s *Config) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts RetentionConfig to a Tony IR node.
func (s *RetentionConfig) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Every
	if txt, err := s.Every.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "Every", err)
	} else {
		irMap["every"] = ir.FromString(string(txt))
	}

	// Field: Batch
	irMap["batch"] = ir.FromInt(int64(s.Batch))

	// Field: Author
	irMap["author"] = ir.FromString(string(s.Author))

	// Field: Rules
	{
		slice := make([]*ir.Node, len(s.Rules))
		for i, v := range s.Rules {
			node, err = v.ToTonyIR(opts...)
			if err != nil {
				return nil, fmt.Errorf("failed to convert slice element %d: %w", i, err)
			}
			slice[i] = node
		}
		irMap["rules"] = ir.FromSlice(slice)
	}

	return ir.FromMap(irMap).WithTag("!retention-config"), nil
}

// FromTonyIR populates RetentionConfig from a Tony IR node.
func (s *RetentionConfig) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for RetentionConfig, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "every":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "every", fieldNodeUnwrapped.Type)
			}
			if err := s.Every.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "every", err)
			}
		case "batch":
			// Field: Batch
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "batch", fieldNodeUnwrapped.Type)
			}
			s.Batch = int(*fieldNodeUnwrapped.Int64)
		case "author":
			// Field: Author
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "author", fieldNodeUnwrapped.Type)
			}
			s.Author = string(fieldNodeUnwrapped.String)
		case "rules":
			// Field: Rules
			if fieldNodeUnwrapped.Type == ir.ArrayType {
				slice := make([]*RetentionRule, len(fieldNodeUnwrapped.Values))
				for i, v := range fieldNodeUnwrapped.Values {
					elem := new(RetentionRule)
					if err := elem.FromTonyIR(v, opts...); err != nil {
						return fmt.Errorf("failed to convert slice element %d: %w", i, err)
					}
					slice[i] = elem
				}
				s.Rules = slice
			} else {
				return fmt.Errorf("%s: expected array, got %v", "field \"rules\"", fieldNodeUnwrapped.Type)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for RetentionConfig", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts RetentionConfig to Tony format bytes.
func (s *RetentionConfig) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates RetentionConfig.
func (s *RetentionConfig) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts RetentionRule to a Tony IR node.
func (s *RetentionRule) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Path
	irMap["path"] = ir.FromString(string(s.Path))

	// Field: Match (optional)
	if s.Match != nil {
		irMap["match"] = s.Match
	}

	// Field: Age
	irMap["age"] = ir.FromString(string(s.Age))

	// Field: After
	if txt, err := s.After.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "After", err)
	} else {
		irMap["after"] = ir.FromString(string(txt))
	}

	return ir.FromMap(irMap).WithTag("!retention-rule"), nil
}

// FromTonyIR populates RetentionRule from a Tony IR node.
func (s *RetentionRule) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for RetentionRule, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "path":
			// Field: Path
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "path", fieldNodeUnwrapped.Type)
			}
			s.Path = string(fieldNodeUnwrapped.String)
		case "match":
			if gomap.GetUnmapComments(opts...) {
				s.Match = fieldNode
			} else {
				s.Match = fieldNodeUnwrapped
			}
		case "age":
			// Field: Age
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "age", fieldNodeUnwrapped.Type)
			}
			s.Age = string(fieldNodeUnwrapped.String)
		case "after":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "after", fieldNodeUnwrapped.Type)
			}
			if err := s.After.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "after", err)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for RetentionRule", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts RetentionRule to Tony format bytes.
func (s *RetentionRule) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates RetentionRule.
func (s *RetentionRule) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts StorageConfig to a Tony IR node.
func (s *StorageConfig) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Durability
	irMap["durability"] = ir.FromString(string(s.Durability))

	// Field: ReadBudget
	irMap["readBudget"] = ir.FromInt(int64(s.ReadBudget))

	// Field: WriteBudget
	irMap["writeBudget"] = ir.FromInt(int64(s.WriteBudget))

	// Field: PathSnapshotTail
	irMap["pathSnapshotTail"] = ir.FromInt(int64(s.PathSnapshotTail))

	// Field: PathSnapshotBytes
	irMap["pathSnapshotBytes"] = ir.FromInt(int64(s.PathSnapshotBytes))

	// Field: IndexCeiling
	irMap["indexCeiling"] = ir.FromInt(int64(s.IndexCeiling))

	return ir.FromMap(irMap).WithTag("!storage-config"), nil
}

// FromTonyIR populates StorageConfig from a Tony IR node.
func (s *StorageConfig) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for StorageConfig, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "durability":
			// Field: Durability
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "durability", fieldNodeUnwrapped.Type)
			}
			s.Durability = string(fieldNodeUnwrapped.String)
		case "readBudget":
			// Field: ReadBudget
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "readBudget", fieldNodeUnwrapped.Type)
			}
			s.ReadBudget = int64(*fieldNodeUnwrapped.Int64)
		case "writeBudget":
			// Field: WriteBudget
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "writeBudget", fieldNodeUnwrapped.Type)
			}
			s.WriteBudget = int64(*fieldNodeUnwrapped.Int64)
		case "pathSnapshotTail":
			// Field: PathSnapshotTail
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "pathSnapshotTail", fieldNodeUnwrapped.Type)
			}
			s.PathSnapshotTail = int64(*fieldNodeUnwrapped.Int64)
		case "pathSnapshotBytes":
			// Field: PathSnapshotBytes
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "pathSnapshotBytes", fieldNodeUnwrapped.Type)
			}
			s.PathSnapshotBytes = int64(*fieldNodeUnwrapped.Int64)
		case "indexCeiling":
			// Field: IndexCeiling
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "indexCeiling", fieldNodeUnwrapped.Type)
			}
			s.IndexCeiling = int64(*fieldNodeUnwrapped.Int64)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for StorageConfig", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts StorageConfig to Tony format bytes.
func (s *StorageConfig) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates StorageConfig.
func (s *StorageConfig) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts TxConfig to a Tony IR node.
func (s *TxConfig) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Timeout
	if txt, err := s.Timeout.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "Timeout", err)
	} else {
		irMap["timeout"] = ir.FromString(string(txt))
	}

	return ir.FromMap(irMap).WithTag("!tx-config"), nil
}

// FromTonyIR populates TxConfig from a Tony IR node.
func (s *TxConfig) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for TxConfig, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "timeout":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "timeout", fieldNodeUnwrapped.Type)
			}
			if err := s.Timeout.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "timeout", err)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for TxConfig", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts TxConfig to Tony format bytes.
func (s *TxConfig) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates TxConfig.
func (s *TxConfig) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts SnapshotConfig to a Tony IR node.
func (s *SnapshotConfig) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: MaxCommits
	irMap["maxCommits"] = ir.FromInt(int64(s.MaxCommits))

	// Field: MaxBytes
	irMap["maxBytes"] = ir.FromInt(int64(s.MaxBytes))

	return ir.FromMap(irMap).WithTag("!snapshot-config"), nil
}

// FromTonyIR populates SnapshotConfig from a Tony IR node.
func (s *SnapshotConfig) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for SnapshotConfig, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "maxCommits":
			// Field: MaxCommits
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "maxCommits", fieldNodeUnwrapped.Type)
			}
			s.MaxCommits = int64(*fieldNodeUnwrapped.Int64)
		case "maxBytes":
			// Field: MaxBytes
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "maxBytes", fieldNodeUnwrapped.Type)
			}
			s.MaxBytes = int64(*fieldNodeUnwrapped.Int64)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for SnapshotConfig", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts SnapshotConfig to Tony format bytes.
func (s *SnapshotConfig) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates SnapshotConfig.
func (s *SnapshotConfig) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts CompactionConfig to a Tony IR node.
func (s *CompactionConfig) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Cutoff
	if txt, err := s.Cutoff.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "Cutoff", err)
	} else {
		irMap["cutoff"] = ir.FromString(string(txt))
	}

	// Field: BaseInterval
	if txt, err := s.BaseInterval.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "BaseInterval", err)
	} else {
		irMap["baseInterval"] = ir.FromString(string(txt))
	}

	// Field: SlotsPerTier
	irMap["slotsPerTier"] = ir.FromInt(int64(s.SlotsPerTier))

	// Field: Multiplier
	irMap["multiplier"] = ir.FromInt(int64(s.Multiplier))

	// Field: GracePeriod
	if txt, err := s.GracePeriod.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "GracePeriod", err)
	} else {
		irMap["gracePeriod"] = ir.FromString(string(txt))
	}

	// Field: Horizon
	if txt, err := s.Horizon.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "Horizon", err)
	} else {
		irMap["horizon"] = ir.FromString(string(txt))
	}

	return ir.FromMap(irMap).WithTag("!compaction-config"), nil
}

// FromTonyIR populates CompactionConfig from a Tony IR node.
func (s *CompactionConfig) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for CompactionConfig, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "cutoff":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "cutoff", fieldNodeUnwrapped.Type)
			}
			if err := s.Cutoff.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "cutoff", err)
			}
		case "baseInterval":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "baseInterval", fieldNodeUnwrapped.Type)
			}
			if err := s.BaseInterval.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "baseInterval", err)
			}
		case "slotsPerTier":
			// Field: SlotsPerTier
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "slotsPerTier", fieldNodeUnwrapped.Type)
			}
			s.SlotsPerTier = int(*fieldNodeUnwrapped.Int64)
		case "multiplier":
			// Field: Multiplier
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "multiplier", fieldNodeUnwrapped.Type)
			}
			s.Multiplier = int(*fieldNodeUnwrapped.Int64)
		case "gracePeriod":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "gracePeriod", fieldNodeUnwrapped.Type)
			}
			if err := s.GracePeriod.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "gracePeriod", err)
			}
		case "horizon":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "horizon", fieldNodeUnwrapped.Type)
			}
			if err := s.Horizon.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "horizon", err)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for CompactionConfig", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts CompactionConfig to Tony format bytes.
func (s *CompactionConfig) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates CompactionConfig.
func (s *CompactionConfig) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
