// Code generated by tony-codegen. DO NOT EDIT.

package ptrslice

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts PS to a Tony IR node.
func (s *PS) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Probe (optional)
	if s.Probe != nil {
		if s.Probe != nil {
			var node *ir.Node
			ns0 := make([]*ir.Node, len((*s.Probe)))
			for i0, e0 := range *s.Probe {
				var en0 *ir.Node
				en0 = ir.FromString(string(e0))
				ns0[i0] = en0
			}
			node = ir.FromSlice(ns0)
			irMap["probe"] = node
		}
	}

	// Field: Ports (optional)
	if s.Ports != nil {
		if s.Ports != nil {
			var node *ir.Node
			ns0 := make([]*ir.Node, len((*s.Ports)))
			for i0, e0 := range *s.Ports {
				var en0 *ir.Node
				en0 = ir.FromInt(int64(e0))
				ns0[i0] = en0
			}
			node = ir.FromSlice(ns0)
			irMap["ports"] = node
		}
	}

	// Field: Steps (optional)
	if s.Steps != nil {
		if s.Steps != nil {
			var node *ir.Node
			ns0 := make([]*ir.Node, len((*s.Steps)))
			for i0, e0 := range *s.Steps {
				var en0 *ir.Node
				n1, err := e0.ToTonyIR(opts...)
				if err != nil {
					return nil, err
				}
				en0 = n1
				ns0[i0] = en0
			}
			node = ir.FromSlice(ns0)
			irMap["steps"] = node
		}
	}

	// Field: Plain
	if len(s.Plain) > 0 {
		slice := make([]*ir.Node, len(s.Plain))
		for i, v := range s.Plain {
			slice[i] = ir.FromString(string(v))
		}
		irMap["plain"] = ir.FromSlice(slice)
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates PS from a Tony IR node.
func (s *PS) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for PS, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "probe":
			// Field: Probe
			if fieldNodeUnwrapped.Type != ir.NullType {
				var d0 []string
				if fieldNodeUnwrapped.Type == ir.ArrayType {
					sl1 := make([]string, len(fieldNodeUnwrapped.Values))
					for i1, v1 := range fieldNodeUnwrapped.Values {
						var e1 string
						var x2 string
						if v1.Type != ir.StringType {
							return fmt.Errorf("%s: expected string, got %v", fmt.Sprintf("%s: element %d", "field \"probe\"", i1), v1.Type)
						}
						x2 = v1.String
						e1 = string(x2)
						sl1[i1] = e1
					}
					d0 = sl1
				} else {
					return fmt.Errorf("%s: expected array, got %v", "field \"probe\"", fieldNodeUnwrapped.Type)
				}
				s.Probe = &d0
			}
		case "ports":
			// Field: Ports
			if fieldNodeUnwrapped.Type != ir.NullType {
				var d0 []int
				if fieldNodeUnwrapped.Type == ir.ArrayType {
					sl1 := make([]int, len(fieldNodeUnwrapped.Values))
					for i1, v1 := range fieldNodeUnwrapped.Values {
						var e1 int
						var x2 int
						if v1.Int64 == nil {
							return fmt.Errorf("%s: expected number, got %v", fmt.Sprintf("%s: element %d", "field \"ports\"", i1), v1.Type)
						}
						x2 = int(*v1.Int64)
						e1 = int(x2)
						sl1[i1] = e1
					}
					d0 = sl1
				} else {
					return fmt.Errorf("%s: expected array, got %v", "field \"ports\"", fieldNodeUnwrapped.Type)
				}
				s.Ports = &d0
			}
		case "steps":
			// Field: Steps
			if fieldNodeUnwrapped.Type != ir.NullType {
				var d0 []Step
				if fieldNodeUnwrapped.Type == ir.ArrayType {
					sl1 := make([]Step, len(fieldNodeUnwrapped.Values))
					for i1, v1 := range fieldNodeUnwrapped.Values {
						var e1 Step
						st2 := Step{}
						if err := st2.FromTonyIR(v1, opts...); err != nil {
							return fmt.Errorf("%s: %w", fmt.Sprintf("%s: element %d", "field \"steps\"", i1), err)
						}
						e1 = st2
						sl1[i1] = e1
					}
					d0 = sl1
				} else {
					return fmt.Errorf("%s: expected array, got %v", "field \"steps\"", fieldNodeUnwrapped.Type)
				}
				s.Steps = &d0
			}
		case "plain":
			// Field: Plain
			if fieldNodeUnwrapped.Type == ir.ArrayType {
				slice := make([]string, len(fieldNodeUnwrapped.Values))
				for i, v := range fieldNodeUnwrapped.Values {
					ctx := fmt.Sprintf("slice element %d", i)
					var elem string
					if v.Type != ir.StringType {
						return fmt.Errorf("%s: expected string, got %v", ctx, v.Type)
					}
					elem = v.String
					slice[i] = string(elem)
				}
				s.Plain = slice
			} else {
				return fmt.Errorf("%s: expected array, got %v", "field \"plain\"", fieldNodeUnwrapped.Type)
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for PS", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts PS to Tony format bytes.
func (s *PS) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates PS.
func (s *PS) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts Step to a Tony IR node.
func (s *Step) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Name
	irMap["name"] = ir.FromString(string(s.Name))

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Step from a Tony IR node.
func (s *Step) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Step, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "name":
			// Field: Name
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "name", fieldNodeUnwrapped.Type)
			}
			s.Name = string(fieldNodeUnwrapped.String)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Step", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Step to Tony format bytes.
func (s *Step) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Step.
func (s *Step) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
