// Code generated by tony-codegen. DO NOT EDIT.

package index

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts LogSegment to a Tony IR node.
func (s *LogSegment) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: StartCommit
	irMap["StartCommit"] = ir.FromInt(int64(s.StartCommit))

	// Field: StartTx
	irMap["StartTx"] = ir.FromInt(int64(s.StartTx))

	// Field: EndCommit
	irMap["EndCommit"] = ir.FromInt(int64(s.EndCommit))

	// Field: EndTx
	irMap["EndTx"] = ir.FromInt(int64(s.EndTx))

	// Field: KindedPath
	irMap["KindedPath"] = ir.FromString(string(s.KindedPath))

	// Field: ArrayKey (optional)
	if s.ArrayKey != nil {
		irMap["ArrayKey"] = s.ArrayKey
	}

	// Field: ArrayKeyField
	irMap["ArrayKeyField"] = ir.FromString(string(s.ArrayKeyField))

	// Field: LogFile
	irMap["LogFile"] = ir.FromString(string(s.LogFile))

	// Field: LogPosition
	irMap["LogPosition"] = ir.FromInt(int64(s.LogPosition))

	// Field: LogFileGeneration
	irMap["LogFileGeneration"] = ir.FromInt(int64(s.LogFileGeneration))

	// Field: ScopeID (optional)
	if s.ScopeID != nil {
		irMap["ScopeID"] = ir.FromString(string(*s.ScopeID))
	}

	// Field: ScopeOverlay
	irMap["ScopeOverlay"] = ir.FromBool(bool(s.ScopeOverlay))

	return ir.FromMap(irMap).WithTag("!log-segment"), nil
}

// FromTonyIR populates LogSegment from a Tony IR node.
func (s *LogSegment) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for LogSegment, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "StartCommit":
			// Field: StartCommit
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "StartCommit", fieldNodeUnwrapped.Type)
			}
			s.StartCommit = int64(*fieldNodeUnwrapped.Int64)
		case "StartTx":
			// Field: StartTx
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "StartTx", fieldNodeUnwrapped.Type)
			}
			s.StartTx = int64(*fieldNodeUnwrapped.Int64)
		case "EndCommit":
			// Field: EndCommit
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "EndCommit", fieldNodeUnwrapped.Type)
			}
			s.EndCommit = int64(*fieldNodeUnwrapped.Int64)
		case "EndTx":
			// Field: EndTx
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "EndTx", fieldNodeUnwrapped.Type)
			}
			s.EndTx = int64(*fieldNodeUnwrapped.Int64)
		case "KindedPath":
			// Field: KindedPath
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "KindedPath", fieldNodeUnwrapped.Type)
			}
			s.KindedPath = string(fieldNodeUnwrapped.String)
		case "ArrayKey":
			if gomap.GetUnmapComments(opts...) {
				s.ArrayKey = fieldNode
			} else {
				s.ArrayKey = fieldNodeUnwrapped
			}
		case "ArrayKeyField":
			// Field: ArrayKeyField
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "ArrayKeyField", fieldNodeUnwrapped.Type)
			}
			s.ArrayKeyField = string(fieldNodeUnwrapped.String)
		case "LogFile":
			// Field: LogFile
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "LogFile", fieldNodeUnwrapped.Type)
			}
			s.LogFile = string(fieldNodeUnwrapped.String)
		case "LogPosition":
			// Field: LogPosition
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "LogPosition", fieldNodeUnwrapped.Type)
			}
			s.LogPosition = int64(*fieldNodeUnwrapped.Int64)
		case "LogFileGeneration":
			// Field: LogFileGeneration
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "LogFileGeneration", fieldNodeUnwrapped.Type)
			}
			s.LogFileGeneration = int64(*fieldNodeUnwrapped.Int64)
		case "ScopeID":
			// Field: ScopeID
			if fieldNodeUnwrapped.Type == ir.NullType {
				// null value - leave pointer as nil
			} else {
				val := new(string)
				if fieldNodeUnwrapped.Type != ir.StringType {
					return fmt.Errorf("%s: expected string, got %v", "field \"ScopeID\"", fieldNodeUnwrapped.Type)
				}
				*val = string(fieldNodeUnwrapped.String)
				s.ScopeID = val
			}
		case "ScopeOverlay":
			// Field: ScopeOverlay
			if fieldNodeUnwrapped.Type != ir.BoolType {
				return fmt.Errorf("field %q: expected bool, got %v", "ScopeOverlay", fieldNodeUnwrapped.Type)
			}
			s.ScopeOverlay = bool(fieldNodeUnwrapped.Bool)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for LogSegment", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts LogSegment to Tony format bytes.
func (s *LogSegment) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates LogSegment.
func (s *LogSegment) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
