// Code generated by tony-codegen. DO NOT EDIT.

package index

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts LogSegment to a Tony IR node.
func (s *LogSegment) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: StartCommit
	irMap["StartCommit"] = ir.FromInt(int64(s.StartCommit))

	// Field: StartTx
	irMap["StartTx"] = ir.FromInt(int64(s.StartTx))

	// Field: EndCommit
	irMap["EndCommit"] = ir.FromInt(int64(s.EndCommit))

	// Field: EndTx
	irMap["EndTx"] = ir.FromInt(int64(s.EndTx))

	// Field: RelPath
	irMap["RelPath"] = ir.FromString(s.RelPath)

	// Create IR node with schema tag
	return ir.FromMap(irMap).WithTag("!log-segment"), nil
}

// FromTonyIR populates LogSegment from a Tony IR node.
func (s *LogSegment) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for LogSegment, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		switch fieldName.String {
		case "StartCommit":
			// Field: StartCommit
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "StartCommit", fieldNode.Type)
			}
			s.StartCommit = int64(*fieldNode.Int64)
		case "StartTx":
			// Field: StartTx
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "StartTx", fieldNode.Type)
			}
			s.StartTx = int64(*fieldNode.Int64)
		case "EndCommit":
			// Field: EndCommit
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "EndCommit", fieldNode.Type)
			}
			s.EndCommit = int64(*fieldNode.Int64)
		case "EndTx":
			// Field: EndTx
			if fieldNode.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "EndTx", fieldNode.Type)
			}
			s.EndTx = int64(*fieldNode.Int64)
		case "RelPath":
			// Field: RelPath
			if fieldNode.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "RelPath", fieldNode.Type)
			}
			s.RelPath = fieldNode.String
		}
	}

	return nil
}

// ToTony converts LogSegment to Tony format bytes.
func (s *LogSegment) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates LogSegment.
func (s *LogSegment) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
