// Code generated by tony-codegen. DO NOT EDIT.

package namedint

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
	"time"
)

// ToTonyIR converts Host to a Tony IR node.
func (s *Host) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: L
	irMap["l"] = ir.FromInt(int64(s.L))

	// Field: P (optional)
	if s.P != nil {
		irMap["p"] = ir.FromInt(int64(*s.P))
	}

	// Field: D
	if s.D != 0 {
		irMap["d"] = ir.FromInt(int64(s.D))
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Host from a Tony IR node.
func (s *Host) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Host, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "l":
			// Field: L
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "l", fieldNodeUnwrapped.Type)
			}
			s.L = Level(*fieldNodeUnwrapped.Int64)
		case "p":
			// Field: P
			if fieldNodeUnwrapped.Type == ir.NullType {
				// null value - leave pointer as nil
			} else {
				val := new(Level)
				if fieldNodeUnwrapped.Int64 == nil {
					return fmt.Errorf("%s: expected number, got %v", "field \"p\"", fieldNodeUnwrapped.Type)
				}
				*val = Level(*fieldNodeUnwrapped.Int64)
				s.P = val
			}
		case "d":
			// Field: D
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "d", fieldNodeUnwrapped.Type)
			}
			s.D = time.Duration(*fieldNodeUnwrapped.Int64)
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Host", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Host to Tony format bytes.
func (s *Host) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Host.
func (s *Host) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
