package gomap

import (
	"reflect"
	"runtime"
	"sync"
)

// Go promotes an embedded field's methods onto the outer struct, so a plain
// MethodByName("ToTonyIR") succeeds on a struct that merely EMBEDS a
// codec-bearing type. Dispatching on that hands the embedded type's codec the
// whole value, and the outer struct's own fields are never visited — silently,
// and symmetrically on decode, so a round trip is self-consistent and wrong.
//
// reflect offers no way to ask where a method was declared, so we ask the
// runtime instead: a promoted method is a compiler-generated wrapper, and
// wrappers report "<autogenerated>" as their source file.
//
// That test alone is not enough. A value-receiver method reached through the
// pointer type is also a wrapper — *T.M is generated for func (T) M — so
// *Shadow.M reads as autogenerated even when Shadow declares M itself.
// Consulting the value type first settles that case, and every case in which a
// type cannot promote anything at all is answered without the runtime.
const autogeneratedFile = "<autogenerated>"

type methodOrigin struct {
	typ  reflect.Type
	name string
}

var declaredMethods sync.Map // methodOrigin -> bool

// declaresMethod reports whether typ's own definition declares name, as opposed
// to inheriting it by promotion from an embedded field. Pointer types answer for
// the type they point at.
//
// It is deliberately biased towards true: a type that can promote nothing, and a
// method the runtime cannot place, both count as declared, so the answer only
// ever diverges from a plain MethodByName for the shape this exists to catch.
func declaresMethod(typ reflect.Type, name string) bool {
	key := methodOrigin{typ: typ, name: name}
	if cached, ok := declaredMethods.Load(key); ok {
		return cached.(bool)
	}
	declared := lookupDeclaresMethod(typ, name)
	declaredMethods.Store(key, declared)
	return declared
}

func lookupDeclaresMethod(typ reflect.Type, name string) bool {
	base := typ
	if base.Kind() == reflect.Ptr {
		base = base.Elem()
	}
	if !canPromote(base) {
		return true
	}
	// A value receiver reads correctly on the value type; only then is a wrapper
	// on the pointer type evidence of a pointer receiver rather than promotion.
	if declaredOn(base, name) {
		return true
	}
	return declaredOn(reflect.PointerTo(base), name)
}

// canPromote reports whether base can inherit a method from an embedded field.
// Only a struct with at least one anonymous field can.
func canPromote(base reflect.Type) bool {
	if base.Kind() != reflect.Struct {
		return false
	}
	for i := 0; i < base.NumField(); i++ {
		if base.Field(i).Anonymous {
			return true
		}
	}
	return false
}

// soleEmbeddedField returns the index of typ's only embedded struct field, when
// that field is the whole of what typ has to serialize.
//
// Such a type is a wrapper — `type MyTime struct{ time.Time }`, written to hang
// methods off a type from elsewhere — and it stands or falls with the value it
// wraps. That matters when the embedded type's wire form is not an object: there
// is no parent object to merge a scalar into, but there is also nothing to lose
// by letting the scalar be the whole encoding, which is what a promoted
// MarshalText used to do here and what encoding/json still does.
//
// The answer depends only on the type, never on the value, so a wrapper does not
// encode as a scalar for one value and fail for the next.
func soleEmbeddedField(typ reflect.Type) ([]int, bool) {
	var index []int
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if !field.Anonymous {
			if field.IsExported() {
				return nil, false // a field of its own: it is not just a wrapper
			}
			continue
		}
		if field.Type.Kind() != reflect.Struct {
			continue // anonymous non-struct fields carry schema tags, not data
		}
		if index != nil {
			return nil, false // more than one embedded struct
		}
		index = field.Index
	}
	return index, index != nil
}

// declaredOn reports whether recv has name as a method written against recv
// itself, rather than as a compiler-generated wrapper.
func declaredOn(recv reflect.Type, name string) bool {
	m, ok := recv.MethodByName(name)
	if !ok {
		return false
	}
	pc := m.Func.Pointer()
	fn := runtime.FuncForPC(pc)
	if fn == nil {
		// A toolchain we cannot read: keep the historical behaviour and dispatch.
		return true
	}
	file, _ := fn.FileLine(pc)
	return file != autogeneratedFile
}
