// Code generated by tony-codegen. DO NOT EDIT.

package pkg3

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Inner to a Tony IR node.
func (s *Inner) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: A
	if txt, err := s.A.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "A", err)
	} else {
		irMap["A"] = ir.FromString(string(txt))
	}

	// Create IR node with schema tag
	return ir.FromMap(irMap).WithTag("!inner"), nil
}

// FromTonyIR populates Inner from a Tony IR node.
func (s *Inner) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Inner, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		switch fieldName.String {
		case "A":
			if fieldNode.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "A", fieldNode.Type)
			}
			if err := s.A.UnmarshalText([]byte(fieldNode.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "A", err)
			}
		}
	}

	return nil
}

// ToTony converts Inner to Tony format bytes.
func (s *Inner) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Inner.
func (s *Inner) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
