package main

import (
	"fmt"
	"strings"

	"github.com/scott-cotton/cli"
)

// Shell completion, written from the command tree rather than kept beside it.
//
// The tree is the only thing that has the list: MainCommand lives in package main,
// so nothing outside this binary can walk it -- which is what `o docs` already
// relies on, and it means a completion script cannot name a command o does not
// have, or miss one it does. A hand-written script would be a second copy of the
// tree, and the second copy is the one that goes stale.
//
// What is completed is what a shell can know without reading a document: command
// names, and the options each command takes, its inherited ones included. A path
// into a document is not completed, because completing one means parsing the file
// the user has not finished naming yet.

// CompletionConfig configures `o completion`.
type CompletionConfig struct {
	*MainConfig
	Completion *cli.Command
}

// CompletionCommand writes a completion script for a shell.
func CompletionCommand(mainCfg *MainConfig) *cli.Command {
	cfg := &CompletionConfig{MainConfig: mainCfg}
	opts, err := cli.StructOpts(cfg)
	if err != nil {
		panic(err)
	}
	cmd := cli.NewCommand("completion").
		WithSynopsis("completion bash|zsh|fish").
		WithDescription(completionDesc).
		WithOpts(opts...).
		WithRun(func(cc *cli.Context, args []string) error {
			return completion(cfg, cc, args)
		})
	cfg.Completion = cmd
	return cmd
}

const completionDesc = `Write a shell completion script

The script is generated from the command tree in this binary, so it completes the
commands and options this o has, rather than the ones some other copy had.

    o completion zsh  > "${fpath[1]}/_o"          # zsh
    o completion bash > /etc/bash_completion.d/o  # bash
    source <(o completion bash)                   # bash, this shell only
    o completion fish > ~/.config/fish/completions/o.fish

Commands and options are completed; a path into a document is not, since knowing
one means reading a file the command line has not finished naming.`

func completion(cfg *CompletionConfig, cc *cli.Context, args []string) error {
	args, err := cfg.Completion.Parse(cc, args)
	if err != nil {
		cfg.Completion.Usage(cc, err)
		return cli.ExitCodeErr(2)
	}
	if helpAsked(cfg.Completion, cc, cfg.Help) {
		return nil
	}
	if len(args) != 1 {
		return usageErr(cfg.Completion, cc, "completion takes one argument: bash, zsh or fish")
	}
	root := cfg.Main
	var script string
	switch args[0] {
	case "bash":
		script = bashCompletion(root)
	case "zsh":
		script = zshCompletion(root)
	case "fish":
		script = fishCompletion(root)
	default:
		return usageErr(cfg.Completion, cc, fmt.Sprintf("no completion for %q: bash, zsh or fish", args[0]))
	}
	if _, err := cc.Out.Write([]byte(script)); err != nil {
		return fault(cc, err)
	}
	return nil
}

// subCommands are the commands a completion offers, aliases left out: an alias is
// for typing, and a completion is what saves the typing.
func subCommands(root *cli.Command) []*cli.Command {
	return root.Children
}

func bashCompletion(root *cli.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# bash completion for o, generated by `o completion bash`\n")
	fmt.Fprintf(&b, "_o() {\n")
	fmt.Fprintf(&b, "  local cur prev cmd\n")
	fmt.Fprintf(&b, "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "  cmd=\"\"\n")
	fmt.Fprintf(&b, "  local i\n")
	fmt.Fprintf(&b, "  for ((i=1; i<COMP_CWORD; i++)); do\n")
	fmt.Fprintf(&b, "    case \"${COMP_WORDS[i]}\" in -*) ;; *) cmd=\"${COMP_WORDS[i]}\"; break ;; esac\n")
	fmt.Fprintf(&b, "  done\n")
	fmt.Fprintf(&b, "  if [ -z \"$cmd\" ]; then\n")
	fmt.Fprintf(&b, "    COMPREPLY=( $(compgen -W '%s %s' -- \"$cur\") )\n",
		strings.Join(commandNames(root, false), " "), strings.Join(optionNames(root), " "))
	fmt.Fprintf(&b, "    return\n  fi\n")
	fmt.Fprintf(&b, "  case \"$cmd\" in\n")
	for _, c := range subCommands(root) {
		fmt.Fprintf(&b, "    %s) COMPREPLY=( $(compgen -W '%s' -- \"$cur\") ) ;;\n",
			c.Name, strings.Join(optionNames(c), " "))
	}
	fmt.Fprintf(&b, "  esac\n")
	// A file is what most arguments are, so offer them alongside whatever matched.
	fmt.Fprintf(&b, "  COMPREPLY+=( $(compgen -f -- \"$cur\") )\n")
	fmt.Fprintf(&b, "}\ncomplete -F _o o\n")
	return b.String()
}

func zshCompletion(root *cli.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "#compdef o\n")
	fmt.Fprintf(&b, "# zsh completion for o, generated by `o completion zsh`\n")
	fmt.Fprintf(&b, "_o() {\n")
	fmt.Fprintf(&b, "  local -a commands\n")
	fmt.Fprintf(&b, "  commands=(\n")
	for _, c := range subCommands(root) {
		fmt.Fprintf(&b, "    '%s:%s'\n", c.Name, quoteForShell(oneLine(c.Description)))
	}
	fmt.Fprintf(&b, "  )\n")
	fmt.Fprintf(&b, "  if (( CURRENT == 2 )); then\n")
	fmt.Fprintf(&b, "    _describe -t commands 'o command' commands\n")
	fmt.Fprintf(&b, "    return\n  fi\n")
	fmt.Fprintf(&b, "  case \"${words[2]}\" in\n")
	for _, c := range subCommands(root) {
		fmt.Fprintf(&b, "    %s) _arguments '*:file:_files' %s ;;\n",
			c.Name, zshOptArgs(c))
	}
	fmt.Fprintf(&b, "    *) _files ;;\n")
	fmt.Fprintf(&b, "  esac\n}\n_o \"$@\"\n")
	return b.String()
}

// zshOptArgs renders a command's options as _arguments specs, each with the
// description the option already carries -- which is the point of generating this
// from the tree rather than writing it out.
func zshOptArgs(cmd *cli.Command) string {
	var specs []string
	for _, name := range optionNames(cmd) {
		desc := ""
		if o, ok := cmd.AllOpts()[strings.TrimPrefix(name, "-")]; ok && o != nil {
			desc = oneLine(o.Description)
		}
		specs = append(specs, fmt.Sprintf("'%s[%s]'", name, quoteForShell(desc)))
	}
	return strings.Join(specs, " ")
}

func fishCompletion(root *cli.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# fish completion for o, generated by `o completion fish`\n")
	fmt.Fprintf(&b, "complete -c o -f\n")
	for _, c := range subCommands(root) {
		fmt.Fprintf(&b, "complete -c o -n '__fish_use_subcommand' -a '%s' -d '%s'\n",
			c.Name, quoteForShell(oneLine(c.Description)))
	}
	for _, c := range subCommands(root) {
		for _, name := range optionNames(c) {
			flag := strings.TrimPrefix(name, "-")
			desc := ""
			if o, ok := c.AllOpts()[flag]; ok && o != nil {
				desc = oneLine(o.Description)
			}
			fmt.Fprintf(&b, "complete -c o -n '__fish_seen_subcommand_from %s' -o '%s' -d '%s'\n",
				c.Name, flag, quoteForShell(desc))
		}
	}
	fmt.Fprintf(&b, "complete -c o -n 'not __fish_use_subcommand' -F\n")
	return b.String()
}

// oneLine is the first line of a description, which is what a completion menu has
// room for -- the rest is what `o help <command>` is for.
func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	return strings.TrimSpace(s)
}
