// Code generated by tony-codegen. DO NOT EDIT.

package host

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	lib "github.com/signadot/tony-format/go-tony/gomap/codegen/testdata/pkgnamed/lib-go"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Host to a Tony IR node.
func (s *Host) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: T
	node, err = s.T.ToTonyIR(opts...)
	if err != nil {
		return nil, fmt.Errorf("failed to convert field %q: %w", "T", err)
	}
	irMap["t"] = node

	// Field: P (optional)
	if s.P != nil {
		node, err = s.P.ToTonyIR(opts...)
		if err != nil {
			return nil, err
		}
		irMap["p"] = node
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Host from a Tony IR node.
func (s *Host) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Host, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "t":
			// Field: T
			if err := s.T.FromTonyIR(fieldNode, opts...); err != nil {
				return fmt.Errorf("field %q: %w", "t", err)
			}
		case "p":
			// Field: P
			s.P = &lib.Thing{}
			if err := s.P.FromTonyIR(fieldNode, opts...); err != nil {
				return err
			}
		default:
			if gomap.IsStrict(opts...) {
				return fmt.Errorf("unknown field %q for Host", fieldName.String)
			}
		}
	}

	return nil
}

// ToTony converts Host to Tony format bytes.
func (s *Host) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Host.
func (s *Host) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
