// Code generated by tony-codegen. DO NOT EDIT.

package textscalar

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
)

// ToTonyIR converts Entity to a Tony IR node.
func (s *Entity) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Ref
	if txt, err := s.Ref.MarshalText(); err != nil {
		return nil, fmt.Errorf("failed to marshal field %q: %w", "Ref", err)
	} else {
		irMap["ref"] = ir.FromString(string(txt))
	}

	// Field: Refs
	if len(s.Refs) > 0 {
		slice := make([]*ir.Node, len(s.Refs))
		for i, v := range s.Refs {
			slice[i] = ir.FromInt(int64(v))
		}
		irMap["refs"] = ir.FromSlice(slice)
	}

	// Field: Name
	if s.Name != "" {
		irMap["name"] = ir.FromString(s.Name)
	}

	// Field: Count
	if s.Count != 0 {
		irMap["count"] = ir.FromInt(int64(s.Count))
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Entity from a Tony IR node.
func (s *Entity) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Entity, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "ref":
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string for TextUnmarshaler, got %v", "ref", fieldNodeUnwrapped.Type)
			}
			if err := s.Ref.UnmarshalText([]byte(fieldNodeUnwrapped.String)); err != nil {
				return fmt.Errorf("field %q: failed to unmarshal text: %w", "ref", err)
			}
		case "refs":
			// Field: Refs
			if fieldNodeUnwrapped.Type == ir.ArrayType {
				slice := make([]Ref, len(fieldNodeUnwrapped.Values))
				for i, v := range fieldNodeUnwrapped.Values {
					ctx := fmt.Sprintf("slice element %d", i)
					var elem uint64
					if v.Int64 == nil {
						return fmt.Errorf("%s: expected number, got %v", ctx, v.Type)
					}
					if *v.Int64 < 0 {
						return fmt.Errorf("%s: negative value %d for unsigned type", ctx, *v.Int64)
					}
					elem = uint64(*v.Int64)
					slice[i] = Ref(elem)
				}
				s.Refs = slice
			}
		case "name":
			// Field: Name
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "name", fieldNodeUnwrapped.Type)
			}
			s.Name = fieldNodeUnwrapped.String
		case "count":
			// Field: Count
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "count", fieldNodeUnwrapped.Type)
			}
			if *fieldNodeUnwrapped.Int64 < 0 {
				return fmt.Errorf("field %q: negative value %d for unsigned type", "count", *fieldNodeUnwrapped.Int64)
			}
			s.Count = uint64(*fieldNodeUnwrapped.Int64)
		}
	}

	return nil
}

// ToTony converts Entity to Tony format bytes.
func (s *Entity) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Entity.
func (s *Entity) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
