// Code generated by tony-codegen. DO NOT EDIT.

package structomit

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
	"reflect"
)

// ToTonyIR converts Inner to a Tony IR node.
func (s *Inner) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Kind
	irMap["kind"] = ir.FromString(s.Kind)

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Inner from a Tony IR node.
func (s *Inner) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Inner, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "kind":
			// Field: Kind
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "kind", fieldNodeUnwrapped.Type)
			}
			s.Kind = fieldNodeUnwrapped.String
		}
	}

	return nil
}

// ToTony converts Inner to Tony format bytes.
func (s *Inner) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Inner.
func (s *Inner) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts Config to a Tony IR node.
func (s *Config) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Addr
	irMap["addr"] = ir.FromString(s.Addr)

	// Field: Format (optional)
	if !isZeroValue_Config_Format(s.Format) {
		node, err = s.Format.ToTonyIR(opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to convert field %q: %w", "Format", err)
		}
		irMap["format"] = node
	}

	return ir.FromMap(irMap), nil
}

// FromTonyIR populates Config from a Tony IR node.
func (s *Config) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Config, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "addr":
			// Field: Addr
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "addr", fieldNodeUnwrapped.Type)
			}
			s.Addr = fieldNodeUnwrapped.String
		case "format":
			// Field: Format
			if err := s.Format.FromTonyIR(fieldNode, opts...); err != nil {
				return fmt.Errorf("field %q: %w", "format", err)
			}
		}
	}

	return nil
}

// ToTony converts Config to Tony format bytes.
func (s *Config) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Config.
func (s *Config) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// Zero-value check helpers
func isZeroValue_Config_Format(v Inner) bool {
	return reflect.ValueOf(v).IsZero()
}
