// Code generated by tony-codegen. DO NOT EDIT.

package dlog

import (
	"bytes"
	"fmt"
	"github.com/signadot/tony-format/go-tony/encode"
	"github.com/signadot/tony-format/go-tony/gomap"
	"github.com/signadot/tony-format/go-tony/ir"
	"github.com/signadot/tony-format/go-tony/parse"
	"github.com/signadot/tony-format/go-tony/system/logd/storage/tx"
)

// ToTonyIR converts SchemaEntry to a Tony IR node.
func (s *SchemaEntry) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Schema (optional)
	if s.Schema != nil {
		irMap["Schema"] = s.Schema
	}

	// Field: Status
	irMap["Status"] = ir.FromString(s.Status)

	return ir.FromMap(irMap).WithTag("!schema-entry"), nil
}

// FromTonyIR populates SchemaEntry from a Tony IR node.
func (s *SchemaEntry) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for SchemaEntry, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "Schema":
			if gomap.GetUnmapComments(opts...) {
				s.Schema = fieldNode
			} else {
				s.Schema = fieldNodeUnwrapped
			}
		case "Status":
			// Field: Status
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "Status", fieldNodeUnwrapped.Type)
			}
			s.Status = fieldNodeUnwrapped.String
		}
	}

	return nil
}

// ToTony converts SchemaEntry to Tony format bytes.
func (s *SchemaEntry) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates SchemaEntry.
func (s *SchemaEntry) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}

// ToTonyIR converts Entry to a Tony IR node.
func (s *Entry) ToTonyIR(opts ...gomap.MapOption) (*ir.Node, error) {
	if s == nil {
		return ir.Null(), nil
	}
	var node *ir.Node
	var err error
	_ = node // suppress unused variable error
	_ = err  // suppress unused variable error

	// Create IR object map
	irMap := make(map[string]*ir.Node)

	// Field: Commit
	irMap["Commit"] = ir.FromInt(int64(s.Commit))

	// Field: Timestamp
	irMap["Timestamp"] = ir.FromString(s.Timestamp)

	// Field: Patch (optional)
	if s.Patch != nil {
		irMap["Patch"] = s.Patch
	}

	// Field: TxSource (optional)
	if s.TxSource != nil {
		node, err = s.TxSource.ToTonyIR()
		if err != nil {
			return nil, err
		}
		irMap["TxSource"] = node
	}

	// Field: SnapPos (optional)
	if s.SnapPos != nil {
		irMap["SnapPos"] = ir.FromInt(int64(*s.SnapPos))
	}

	// Field: LastCommit (optional)
	if s.LastCommit != nil {
		irMap["LastCommit"] = ir.FromInt(int64(*s.LastCommit))
	}

	// Field: ScopeID (optional)
	if s.ScopeID != nil {
		irMap["ScopeID"] = ir.FromString(*s.ScopeID)
	}

	// Field: SchemaEntry (optional)
	if s.SchemaEntry != nil {
		node, err = s.SchemaEntry.ToTonyIR()
		if err != nil {
			return nil, err
		}
		irMap["SchemaEntry"] = node
	}

	return ir.FromMap(irMap).WithTag("!entry"), nil
}

// FromTonyIR populates Entry from a Tony IR node.
func (s *Entry) FromTonyIR(node *ir.Node, opts ...gomap.UnmapOption) error {
	if node == nil {
		return nil
	}

	// Unwrap CommentType nodes to get the actual data node
	if node.Type == ir.CommentType {
		if len(node.Values) > 0 {
			node = node.Values[0]
		} else {
			return nil
		}
	}

	if node.Type == ir.NullType {
		return nil
	}
	if node.Type != ir.ObjectType {
		return fmt.Errorf("expected map for Entry, got %v", node.Type)
	}

	for i, fieldName := range node.Fields {
		fieldNode := node.Values[i]
		// Unwrap CommentType for type checking (preserve original for *ir.Node fields)
		fieldNodeUnwrapped := fieldNode
		if fieldNodeUnwrapped.Type == ir.CommentType && len(fieldNodeUnwrapped.Values) > 0 {
			fieldNodeUnwrapped = fieldNodeUnwrapped.Values[0]
		}
		switch fieldName.String {
		case "Commit":
			// Field: Commit
			if fieldNodeUnwrapped.Int64 == nil {
				return fmt.Errorf("field %q: expected number, got %v", "Commit", fieldNodeUnwrapped.Type)
			}
			s.Commit = int64(*fieldNodeUnwrapped.Int64)
		case "Timestamp":
			// Field: Timestamp
			if fieldNodeUnwrapped.Type != ir.StringType {
				return fmt.Errorf("field %q: expected string, got %v", "Timestamp", fieldNodeUnwrapped.Type)
			}
			s.Timestamp = fieldNodeUnwrapped.String
		case "Patch":
			if gomap.GetUnmapComments(opts...) {
				s.Patch = fieldNode
			} else {
				s.Patch = fieldNodeUnwrapped
			}
		case "TxSource":
			// Field: TxSource
			s.TxSource = &tx.State{}
			if err := s.TxSource.FromTonyIR(fieldNode); err != nil {
				return err
			}
		case "SnapPos":
			// Field: SnapPos
			if fieldNodeUnwrapped.Type == ir.NullType {
				// null value - leave pointer as nil
			} else {
				val := new(int64)
				if fieldNodeUnwrapped.Int64 == nil {
					return fmt.Errorf("%s: expected number, got %v", "field \"SnapPos\"", fieldNodeUnwrapped.Type)
				}
				*val = int64(*fieldNodeUnwrapped.Int64)
				s.SnapPos = val
			}
		case "LastCommit":
			// Field: LastCommit
			if fieldNodeUnwrapped.Type == ir.NullType {
				// null value - leave pointer as nil
			} else {
				val := new(int64)
				if fieldNodeUnwrapped.Int64 == nil {
					return fmt.Errorf("%s: expected number, got %v", "field \"LastCommit\"", fieldNodeUnwrapped.Type)
				}
				*val = int64(*fieldNodeUnwrapped.Int64)
				s.LastCommit = val
			}
		case "ScopeID":
			// Field: ScopeID
			if fieldNodeUnwrapped.Type == ir.NullType {
				// null value - leave pointer as nil
			} else {
				val := new(string)
				if fieldNodeUnwrapped.Type != ir.StringType {
					return fmt.Errorf("%s: expected string, got %v", "field \"ScopeID\"", fieldNodeUnwrapped.Type)
				}
				*val = string(fieldNodeUnwrapped.String)
				s.ScopeID = val
			}
		case "SchemaEntry":
			// Field: SchemaEntry
			s.SchemaEntry = &SchemaEntry{}
			if err := s.SchemaEntry.FromTonyIR(fieldNode); err != nil {
				return err
			}
		}
	}

	return nil
}

// ToTony converts Entry to Tony format bytes.
func (s *Entry) ToTony(opts ...gomap.MapOption) ([]byte, error) {
	node, err := s.ToTonyIR(opts...)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := encode.Encode(node, &buf, gomap.ToEncodeOptions(opts...)...); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// FromTony parses Tony format bytes and populates Entry.
func (s *Entry) FromTony(data []byte, opts ...gomap.UnmapOption) error {
	node, err := parse.Parse(data, gomap.ToParseOptions(opts...)...)
	if err != nil {
		return err
	}
	return s.FromTonyIR(node, opts...)
}
